{% set version = "0.2.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-drat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/drat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/drat/drat_{{ version }}.tar.gz
  sha256: a65e7cd03106c744bfe184dbe7869c2978e67e4cf6bc237e9d8a319924ed3ea4

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('drat')"           # [not win]
    - "\"%R%\" -e \"library('drat')\""  # [win]

about:
  home: http://dirk.eddelbuettel.com/code/drat.html
  license: GPL-2.0-or-later
  summary: 'Creation and use of R Repositories via helper functions to insert packages into a repository, and to add repository information  to the current R session. Two primary types of repositories are support: gh-pages at GitHub, as well as local repositories on either the same machine or a local network. Drat is a recursive
    acronym: Drat R Archive Template.'
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
