appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: hvUZlqFtNlzE8x5DEwy+eI3u+LzhqwjydVLeOZAg+pmHMcomV9qnpGjkeVhLvb+jM+l1WyQIgbOWj8IQowDqlomF5ch7JnHmPjkLFaJdj2cjALAeCb25eP1SQ/PxY4pUVAB5b3Jt39PpuCIzNqJkIKXacgx4W5H51HP1QadOxSCiP9Q8GM4LGAXs0SPhWNSveNsAo1HEIR3UtQm9qlRTAEzSRg+NxZ+XLi6q7PRdjdUUW6u18Nm18HKV9vzBK0MhSsJ82SIvYa//vDMSwlv4zW2lws0+57CqciylAexqAhjXX7ZjuDOaFoDuY6T774BwItWo+D17FZykoZQS3dSviXM7jHXheiCpm0e03mJO6h/xwiJqWUqUWpgoeN1ACIrmQgBvLNlzC7Px7OdIJEOKkCYMvm/YEG1IaZr7LPNTA3gbmEaXKhXe2FbrA6tpVlay5yIDxXlGODO4BeyLd7xDgaqgl5JpgtWLn4+exmMyEN6sb2g1KlCFsc7trcWkQqXvHlKFkHfx6IFHA/iIrlLPg0QhBVxLt9lrxCgC3OgHMBnhxSP9FEpRQCk44QVh/m25xGWUdB3sh6Rvmt+rfZeSr86m+NwkPg68uMg3ApGCLMWQxCbgb1jkh8E4vrn1MXsJUHa+H6wMVO3rt9GUwzoSkODL8JdSKk9ZIIJe9221mDw=}
