travis:
  secure:
    BINSTAR_TOKEN: K4U1+0f//N9olyLEZ/LxchfjzeDxPUBmfF46hwV2Zo8uiHv6RTQsvwib2JQSBzlafu0+fc22oPk59vi7IB8CZ9PdDKpdk7dkJxwqF2zRLicKxMNf7scs90MVULpW/4h4uJm6gySRzqmToc04KabJzKqwXCa41HtWr5jQm+/oQYL0FxiFx0dnT5KhY0QRD01FqnpnwXrqsbRrCgcsLQLdDVB5goT3YDjOyKk5lCvD+MThw4x13JR1/XY8A7XM9t+X7PP7+HnSVH9GuNlySjsg6kkn2L2YUxHx7oN86kCRqKc+UyyiZMnbk3kQgFHGQF6CwVq1PAfCjywStdSRYYMQgiVL/plOdry0QKztIHYk61UN10S8Nw0gPRB4IzwK2sefsIto9oAaarhhUYviWv0B30tzhhmRrF1708UwCnCTfXeGohNpD+DVQ/BcZw6blbcEoGsQ2SMnEcAG2eE8yIrWcKJ5yJ1ProhjuQGuqd4Um7YYlJ9oSI2jjEAJUa0svxXcMd4wn0g0OuUqzYm24q1iea1IseF7qr6VSiJidmwEqJpbgPdUJrqCr/O84y00aLxthVxGhNfvdGQQ92oRTqxlUUWm188hZkQueHR+ybEUm5Ohi6oyFbO182yqR6Pms6Tov30AvjXDR970N50pPvW6umcLljtgmf44x6R2YQsRFZc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
