travis:
  secure:
    BINSTAR_TOKEN: YMG9ZH0HulXVKzO8VmNQhIJ9evNg+PrMUiX9Kg72O6aGdq2JsiSkVlJSmtEWd586IJ1xqLuvaGirG5TDKSjsKDhLslyIvjLiJNkWFPKGI8cqGXyYJZswqQZ7W57iIcnybsAnPCk5z8FI1KZfLVz8l1y3u13aVALnnbKJ0sP/evvNeSxmxpvLRypUUvlgBs0B+XZFnHCW+HQ53rEbZ9VKH5QRqCXV1WzbI29HhdtrX09wTCmziHv1mKBwWmAiyqTHfQHlT6yYSqpuiiJVJxJSQ2nW7Z/VuD2JMNeXD5JTfzI4R5X7e6VlwekJTqf8JmPR8C5z47VAQW3b/oVPLS1iyU2ERvnisojWCbCB4ZOTnnim01JlUN7G8oGBFCZn1HdqSy2iw4hICvRsct5F8FnD8c+e99meKyLuGgyUathjhhoL5gWku+zscd/ZfG6W17qmhhSIY4+T2UZ0+cKywaoGUq/jFSVor56VvlwLQBL01TWrP/FyF1dOoAv2B90Hfe/O7xNxxkldaHW/V734OwkKHwr8wTenY3SjjXMgrr7QFfC++l/4zAJGT4nek+lAk7EjWL1qwMfJpEzuQb9GlhAJJvBy8U5DoKQaYB6fxAqQGl2aClDdyWt8aBqu8Zr9qK50Ms3CQAR/Wsr/54mOc5ptPTyJ3blo2YdhRHymkzBgr4k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
